### ISSUE TITLE
inlineJsConfig

### ISSUE THREAD

**Issue by Repkit** [silvester/ReverseForm#1]
Hi I want to overwrite inlineJsConfig from module.config.php file in my controller.
Basicaly what i want to do is to overwrite some options:
'ReverseForm\Element\GoogleMap' => array(
            'js' => array(
                'https://maps.google.com/maps/api/js?sensor=false&region=SI'
            ),
            'template' => 'googlemap.phtml',
            'inlineJs' => "var map = new google.maps.Map(document.getElementById('%1\$s'), %2\$s);\n$('#%1\$s').data('map', map);\n",
            'inlineJsConfig' => array(
                'zoom'      =>  8,
                'mapTypeId' => new \Zend\Json\Expr('google.maps.MapTypeId.ROADMAP'),
                'center'    => new \Zend\Json\Expr('new google.maps.LatLng(46.15, 14.9)')
            )
        )

here i want to overwrite 'zoom' and 'center' and also to add new vars in my controller. Can you help me with a hint or a piece of code?

**Comment by silvester** [comment]
Hi,

There are many ways to do it. I will write 2 of them here.

1 In the controller after the form is created:

``` php
public function testUniformAction()
{
    $form = new \ReverseForm\Form\TestForm(); // this is a form which is created earlier.
    $gmap = $form->get('gmap'); // get the element you wish
    $gmap->setOptions(array( // set the options
        'extended' => array(
            'js' => array(
                'https://maps.google.com/maps/api/js?sensor=false&region=DE' // can change the url settings
            ),
            'inlineJsConfig' => array( // the init config for the map
                'zoom' =>  15, // change the zoom
                'mapTypeId' => new \Zend\Json\Expr('google.maps.MapTypeId.HYBRID'), // the map type
                'center' => new \Zend\Json\Expr('new google.maps.LatLng(47.15, 15.9)') // the center of the map
             )    
        )    
    ));
    return array('form' => $form);
}
```

2 While you create the form:

``` php
$this->add( // $this is the form which extends zend form.
    array(
        'name' => 'gmap', // element name
        'type' => '\ReverseForm\Element\GoogleMap', // type
        'options' => array(
            'label' => 'Google Map',
            'extended' => array( // extended options which i use for rendering
                'help' => array('content' => 'Some Google Map'),
                'inlineJsConfig' => array( // the init config for the map
                    'zoom' =>  15, // change the zoom
                    'mapTypeId' => new \Zend\Json\Expr('google.maps.MapTypeId.HYBRID'), // the map type
                    'center' => new \Zend\Json\Expr('new google.maps.LatLng(47.15, 15.9)') // the center of the map
                )
            )
        )
    )
);
```

You just change the settings. All config data will be merged in to the element while you render it. This way you can also change the js config to set the location of your js files. You can also change the locations once in your module.config.php, so you dont have to rewrite them everytime.

Lp. Silvester
