### ISSUE TITLE
jquery resource not found

### ISSUE THREAD

**Issue by carpanta** [silvester/ReverseForm#4]
Hi, 

I install it, and almost it works, I only had to do add the slash "\" before the path to the "ReverseForm":

$form = new \ReverseForm\Form\TestForm();

But the jQuery isn't loading because I don't have it installed yet in my vendor folder. I'm wondering how to add the jquery to the vendor folder with the same structure you did or I have to do it manually?

Thanks

**Comment by silvester** [comment]
You have to add js files manually, there is no build strategy. I added a folder called public and a file tree.html which shows the folder structure as I have it. I hope it helps.

**Comment by carpanta** [comment]
Ok, thanks
